### ISSUE TITLE
Need mockup for Hardware info UI

### ISSUE THREAD

**Issue by jordanhubbard** [freenas/gui#16]

**Comment by igor-im** [comment]
I'm not a designer, but I'd be willing to pick up development on this or any other issues you may need

**Comment by jordanhubbard** [comment]
What other experience do you have?  It's hard to know what to suggest...

**Comment by igor-im** [comment]
My dayjob is UI engineer, but I come from full stack background, so really anything with UI or Node.JS I can do. Backend, my main language is C# which I'm sure you guys don't use :), with some forays into Java, Scala and Ruby.

**Comment by igor-im** [comment]
Frontend, I'm comfortable with vanilla JS or most frameworks. Lately been working with React, moving into Flux slowly, and Lodash, also build tools like Webpack.

**Comment by jordanhubbard** [comment]
We're about to rewrite the GUI from scratch - we gave up on the current approach!   Watch this space over the coming months for the new design and implementation.

**Comment by igor-im** [comment]
Cool sounds good :)

**Comment by jordanhubbard** [comment]
Please see the just-released 10-BETA release at http://download.freenas.org/10/BETA -  thanks!
