### ISSUE TITLE
Request: Upgrade to Node.js v5.0.0

### ISSUE THREAD

**Issue by VoR0220** [freenas/gui#20]
Hey guys, I know development is hard underway and that the current way forward seems to be towards 0.12.7 but I was wondering if there was any talk of upgrading node.js to the latest version that complies with new ES6 standards. Not only is this easier to develop in, it also has some pretty neat features going forward and I think it would be well worth the time to examine. Let me know if you need some help in getting dependencies underway for this as I think this would be an excellent feature to add or if there are some dependencies I am unaware of that might make this a no go....basically, I want your thoughts.

**Comment by Fzzr** [comment]
We looked into this as it was being announced. FreeNAS is based on FreeBSD, so any decisions we make depend on what's available in FreeBSD 10. At this time we know we would need certain patches expected to land this month. However, we also have a very bad history with major version revisions mid-project, so we don't intend to take any action on upgrading to Node 5 in the short to medium term.

Thank you for the kind offer.
