### ISSUE TITLE
Proper Add User

### ISSUE THREAD

**Issue by VoR0220** [freenas/gui#22]
When I try to utilize the User form on the FreeNAS GUI to add a user, the gulpfile barfs out this error at me: 

```
[11:00:44]   WEBSERVER   [ STDERR ]
Warning: Failed propType: Required prop `userForm` was not specified in `UserAdd`. Check the render method of `RoutingContext`.


[11:00:44]   WEBSERVER   [ STDERR ]
Warning: Failed propType: Required prop `updateUserForm` was not specified in `UserAdd`. Check the render method of `RoutingContext`.
Warning: Failed propType: Required prop `resetUserForm` was not specified in `UserAdd`. Check the render method of `RoutingContext`.
Warning: Failed propType: Required prop `createUser` was not specified in `UserAdd`. Check the render method of `RoutingContext`.
```

This needs to be fixed...where do I look for the area where this is being worked on?

**Comment by Fzzr** [comment]
Cannot immediately reproduce. Would you post the version string? It's the output of `system version` at the console or the string after "OS VERSION" on the Dashboard. Please also share the settings of the user you tried to add.

**Comment by VoR0220** [comment]
FreeNAS-10.2-ALPHA-201511021130

**Comment by Fzzr** [comment]
Okay. Please update to the latest version, currently FreeNAS-10.2-ALPHA-201512071130. Then, please create a new ticket on https://bugs.freenas.org/projects/freenas-10, which is our primary bug tracker. Make sure to include a complete reproduction case (all the settings in the user creation form submission that causes the failure). Do you have an account on forums.freenas.org? If not I highly recommend getting one there as well.

**Comment by VoR0220** [comment]
alright. Will do. Thank you much.
