### ISSUE TITLE
Safari not rendering the FreeNAS menu correctly

### ISSUE THREAD

**Issue by bsalvador** [freenas/gui#31]
Safari version 9.1.2 is not rendering the FreeNAS left menu on new GUI. Check the pic:
http://imgur.com/a/WgjHY

**Comment by jpaetzel** [comment]
You'll be happy to know that at the moment Chrome is the only web browser supported by the FreeNAS 10 GUI

**Comment by joshuarule** [comment]
Though we are not currently supporting other browsers outside of Chrome at the moment we are continuing to improve cross browser support. The issue you have shown was actually fixed. Maybe you are not running the most current version of the Alpha?
