### ISSUE TITLE
Cron job ui - time periods are not logically displayed

### ISSUE THREAD

**Issue by J-C-B** [freenas/gui#32]
Just a UI / look and feel thing but when configuring a cron job the options are listed in the order below

Days
hours
minutes
months
seconds

months should be first or last so seconds are in the "time" section

love the work you have done, i have kept my blinkers on until the beta and i'm blown away by the features and UI you have created - amazing - great work

**Comment by jordanhubbard** [comment]
Please try a more recent nightly build - we have removed some of the extraneous time fields (like seconds) and reorganized the the calendar.  Please use https://bugs.freenas.org/projects/freenas-10 for reporting / tracking issues any additional issues.  Thanks!
