### ISSUE TITLE
UI has montageLogo in there

### ISSUE THREAD

**Issue by J-C-B** [freenas/gui#33]
may be an easter egg..

but
 in the top left of the web ui - if the freenas logo is clicked ot it scrolls away to show the montage logo

in inspect element it shows as

```<div class="MainSidebar-montageLogo"></div>```

**Comment by joshuarule** [comment]
Yes...it was a bit of an easter egg. We decided to remove Montage Logo and add the IXSystems logo as well as their destination URLS.
