### ISSUE TITLE
Update and reboot flow

### ISSUE THREAD

**Issue by J-C-B** [freenas/gui#44]
webui is clickable but not reactive after using the "update and reboot" button - this is due to actually being logged out, but this not clear to the user

would expect to be prompted to login again after reboot

**Comment by jordanhubbard** [comment]
Please use https://bugs.freenas.org/projects/freenas-10 for reporting / tracking issues.  We only use the github issue tracker for commenting on specific commits or dealing with pull requests.  Thanks.
